DROP TABLE IF EXISTS jti_denylist;
DROP TABLE IF EXISTS refresh_token;
DROP TABLE IF EXISTS role_permission;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS permission;
DROP TABLE IF EXISTS user_totp;
DROP TABLE IF EXISTS app_user;
